spring:
  datasource:
    url: jdbc:postgresql://localhost/user_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs